<?php

declare(strict_types=1);

$finder = PhpCsFixer\Finder::create()
    ->exclude('vendor')
    ->name('*.phtml')
    ->in(__DIR__);

return (new PhpCsFixer\Config())
    ->setParallelConfig(PhpCsFixer\Runner\Parallel\ParallelConfigFactory::detect())
    ->setRiskyAllowed(false)
    ->setFinder($finder)
    ->setCacheFile(sys_get_temp_dir() . '/php-cs-fixer' . preg_replace('~\W~', '-', __DIR__))
    ->setRules([
        'align_multiline_comment' => true,
        'array_indentation' => true,
        'array_push' => false, // Because risk
        'array_syntax' => true,
        'assign_null_coalescing_to_coalesce_equal' => true,
        'backtick_to_shell_exec' => false, // Backticks are a very concise way to execute shell
        'binary_operator_spaces' => true,
        'blank_line_after_namespace' => true,
        'blank_line_after_opening_tag' => true,
        'blank_line_before_statement' => true,
        'braces' => true,
        'cast_spaces' => true,
        'class_attributes_separation' => ['elements' => ['method' => 'one', 'property' => 'one']], // const are often grouped with other related const
        'class_definition' => true,
        'class_keyword_remove' => false, // Deprecated, and ::class keyword gives us better support in IDE
        'combine_consecutive_issets' => true,
        'combine_consecutive_unsets' => true,
        'combine_nested_dirname' => false, // Because risk
        'concat_space' => ['spacing' => 'one'],
        'constant_case' => true,
        'control_structure_continuation_position' => true,
        'date_time_immutable' => false, // Because risk
        'declare_parentheses' => true,
        'declare_strict_types' => false, // Too early to adopt strict types
        'dir_constant' => false, // Because risk
        'doctrine_annotation_braces' => true,
        'doctrine_annotation_indentation' => true,
        'doctrine_annotation_spaces' => true,
        'echo_tag_syntax' => true,
        'elseif' => true,
        'empty_loop_body' => true,
        'empty_loop_condition' => true,
        'encoding' => true,
        'ereg_to_preg' => false, // Because risk
        'explicit_indirect_variable' => false, // I feel it makes the code actually harder to read
        'explicit_string_variable' => false, // I feel it makes the code actually harder to read
        'final_class' => false, // We need non-final classes
        'final_public_method_for_abstract_class' => false, // We need non-final methods
        'fopen_flag_order' => false, // Because risk
        'fully_qualified_strict_types' => true,
        'function_declaration' => true,
        'function_to_constant' => false, // Because risk
        'general_phpdoc_annotation_remove' => ['annotations' => ['author', 'category', 'copyright', 'package', 'throws']],
        'general_phpdoc_tag_rename' => true,
        'global_namespace_import' => true,
        'group_import' => false, // I feel it makes the code actually harder to read
        'header_comment' => false, // We don't use common header in all our files
        'heredoc_indentation' => true,
        'heredoc_to_nowdoc' => false, // We often use variable in heredoc
        'implode_call' => false, // Because risk
        'increment_style' => true,
        'indentation_type' => true,
        'integer_literal_case' => true,
        'is_null' => false, // Because risk
        'line_ending' => true,
        'linebreak_after_opening_tag' => true,
        'list_syntax' => ['syntax' => 'short'],
        'logical_operators' => false, // Because risk
        'lowercase_keywords' => true,
        'lowercase_static_reference' => true,
        'magic_constant_casing' => true,
        'magic_method_casing' => true,
        'mb_str_functions' => false, // Because risk
        'method_chaining_indentation' => true,
        'modernize_strpos' => false, // Require PHP 8.0
        'modernize_types_casting' => false, // Because risk
        'multiline_whitespace_before_semicolons' => true,
        'native_constant_invocation' => false, // Micro optimization that look messy
        'native_function_casing' => true,
        'native_function_invocation' => false, // I suppose this would be best, but I am still unconvinced about the visual aspect of it
        'native_function_type_declaration_casing' => true,
        'new_with_braces' => true,
        'no_alias_functions' => false, // Because risk
        'no_alternative_syntax' => false, // We want to use alternative syntax in .phtml
        'no_binary_string' => true,
        'no_blank_lines_after_class_opening' => true,
        'no_blank_lines_after_phpdoc' => true,
        'no_blank_lines_before_namespace' => false, // we want 1 blank line before namespace
        'no_break_comment' => true,
        'no_closing_tag' => true,
        'no_empty_comment' => true,
        'no_empty_phpdoc' => true,
        'no_empty_statement' => true,
        'no_extra_blank_lines' => true,
        'no_homoglyph_names' => false, // Because risk
        'no_leading_namespace_whitespace' => true,
        'no_mixed_echo_print' => true,
        'no_multiline_whitespace_around_double_arrow' => true,
        'no_null_property_initialization' => true,
        'no_php4_constructor' => false, // Because our BootstrapCli class is affected by https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/3096
        'no_short_bool_cast' => true,
        'no_singleline_whitespace_before_semicolons' => true,
        'no_space_around_double_colon' => true,
        'no_spaces_after_function_name' => true,
        'no_spaces_around_offset' => true,
        'no_spaces_inside_parenthesis' => true,
        'no_superfluous_elseif' => true,
        'no_superfluous_phpdoc_tags' => ['allow_mixed' => true],
        'no_trailing_comma_in_list_call' => true,
        'no_trailing_comma_in_singleline_array' => true,
        'no_trailing_whitespace' => true,
        'no_trailing_whitespace_in_comment' => true,
        'no_trailing_whitespace_in_string' => false, // Too dangerous
        'no_unneeded_control_parentheses' => true,
        'no_unneeded_curly_braces' => true,
        'no_unneeded_final_method' => false, // Because risk
        'no_unset_on_property' => false, // Because risk
        'no_useless_else' => true,
        'no_useless_return' => true,
        'no_whitespace_before_comma_in_array' => true,
        'no_whitespace_in_blank_line' => true,
        'non_printable_character' => false, // Because risk
        'not_operator_with_space' => false, // No we prefer to keep '!' without spaces
        'not_operator_with_successor_space' => false, // idem
        'nullable_type_declaration_for_default_null_value' => true,
        'object_operator_without_whitespace' => true,
        'octal_notation' => true,
        'operator_linebreak' => true,
        'ordered_class_elements' => false, // We prefer to keep some freedom
        'ordered_imports' => true,
        'ordered_interfaces' => false, // Because risk
        'php_unit_internal_class' => false, // Because tests are excluded from package
        'php_unit_method_casing' => false, // Would duplicate method names
        'php_unit_mock' => false, // Because risk
        'php_unit_no_expectation_annotation' => false, // Because risk
        'php_unit_strict' => false, // We sometime actually need assertEquals
        'php_unit_test_annotation' => false, // Because risk
        'phpdoc_add_missing_param_annotation' => true,
        'phpdoc_align' => false, // Waste of time
        'phpdoc_annotation_without_dot' => true,
        'phpdoc_indent' => true,
        'phpdoc_inline_tag_normalizer' => true,
        'phpdoc_line_span' => true,
        'phpdoc_no_access' => true,
        'phpdoc_no_alias_tag' => true,
        'phpdoc_no_empty_return' => true,
        'phpdoc_no_package' => true,
        'phpdoc_no_useless_inheritdoc' => true,
        'phpdoc_order' => true,
        'phpdoc_order_by_value' => true,
        'phpdoc_return_self_reference' => true,
        'phpdoc_scalar' => true,
        'phpdoc_separation' => true,
        'phpdoc_single_line_var_spacing' => true,
        'phpdoc_summary' => true,
        'phpdoc_tag_casing' => true,
        'phpdoc_tag_type' => true,
        'phpdoc_to_comment' => true,
        'phpdoc_to_param_type' => false, // Because experimental, but interesting for one shot use
        'phpdoc_to_property_type' => false, // Because experimental, but interesting for one shot use
        'phpdoc_to_return_type' => false, // Because experimental, but interesting for one shot use
        'phpdoc_trim' => true,
        'phpdoc_trim_consecutive_blank_line_separation' => true,
        'phpdoc_types' => true,
        'phpdoc_types_order' => true,
        'phpdoc_var_annotation_correct_order' => true,
        'phpdoc_var_without_name' => true,
        'pow_to_exponentiation' => false, // Because risk
        'psr_autoloading' => false, // We unfortunately cannot be entirely PSR-0 compliant with ZF1 because of classes like Admin_ChapterController
        'random_api_migration' => false, // Because risk
        'return_type_declaration' => true,
        'self_accessor' => false, // Because risk
        'semicolon_after_instruction' => false, // We prefer to keep .phtml files without semicolon
        'set_type_to_cast' => false, // Because risk
        'simple_to_complex_string_variable' => false, // Would differ from TypeScript without obvious advantages
        'simplified_if_return' => false, // Even if technically correct we prefer to be explicit
        'simplified_null_return' => false, // Even if technically correct we prefer to be explicit
        'single_blank_line_at_eof' => true,
        'single_blank_line_before_namespace' => true,
        'single_class_element_per_statement' => true,
        'single_import_per_statement' => true,
        'single_line_after_imports' => true,
        'single_line_comment_style' => true,
        'single_line_throw' => false, // I don't see any reason for having a special case for Exception
        'single_quote' => true,
        'single_space_after_construct' => true,
        'single_trait_insert_per_statement' => true,
        'space_after_semicolon' => true,
        'standardize_increment' => true,
        'standardize_not_equals' => true,
        'static_lambda' => false, // Risky if we can't guarantee nobody use `bindTo()`
        'strict_comparison' => false, // We sometimes need to compare DateTime objects with non-strict operator
        'strict_param' => false,  // No, too dangerous to change that
        'string_length_to_empty' => false, // Because risk
        'switch_case_space' => true,
        'switch_continue_to_break' => true,
        'ternary_operator_spaces' => true,
        'ternary_to_elvis_operator' => false, // Because risk
        'trailing_comma_in_multiline' => true,
        'trim_array_spaces' => true,
        'types_spaces' => true,
        'unary_operator_spaces' => true,
        'use_arrow_functions' => false, // Because risk
        'void_return' => false, // Because risk
        'yoda_style' => false,
    ]);
